name: CI/CD for Vite React App

on:
  push:
    branches:
      - main  # Runs workflow on push to main branch
  pull_request:
    branches:
      - main  # Runs on PR to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Using Ubuntu latest environment added here

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'  # Use latest LTS version
          cache: 'npm'

      - name: Check Node.js and npm versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Verify dist folder
        run: ls -la dist || echo "⚠️ dist folder is missing!"

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Verify downloaded dist folder
        run: ls -la dist || echo "⚠️ dist folder is missing after download!"

      # - name: Deploy to GitHub Pages
      #   if: success()
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     branch: gh-pages
      #     folder: dist

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN}}
          run: |
          npm install -g vercel
          vercel --prod --token $VERCEL_TOKEN

